// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3H5lA6ndluRU_IpQJXT1ItOiQb0mK4mQ',
    appId: '1:29465398554:web:aa181c3904253187b170a3',
    messagingSenderId: '29465398554',
    projectId: 'finance-a9ef6',
    authDomain: 'finance-a9ef6.firebaseapp.com',
    storageBucket: 'finance-a9ef6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxnCJAiY0d3mn3bkFNNTF854XSAK6H-E',
    appId: '1:29465398554:android:7dcbcb63c00c21fcb170a3',
    messagingSenderId: '29465398554',
    projectId: 'finance-a9ef6',
    storageBucket: 'finance-a9ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBs5BPoKKC6_UFmfCwRQUc5wg7hkGSXo',
    appId: '1:29465398554:ios:4d030c3ab9a66b6eb170a3',
    messagingSenderId: '29465398554',
    projectId: 'finance-a9ef6',
    storageBucket: 'finance-a9ef6.firebasestorage.app',
    iosBundleId: 'com.pietroid.finances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBs5BPoKKC6_UFmfCwRQUc5wg7hkGSXo',
    appId: '1:29465398554:ios:4d030c3ab9a66b6eb170a3',
    messagingSenderId: '29465398554',
    projectId: 'finance-a9ef6',
    storageBucket: 'finance-a9ef6.firebasestorage.app',
    iosBundleId: 'com.pietroid.finances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3H5lA6ndluRU_IpQJXT1ItOiQb0mK4mQ',
    appId: '1:29465398554:web:cc8614dfbd11f9efb170a3',
    messagingSenderId: '29465398554',
    projectId: 'finance-a9ef6',
    authDomain: 'finance-a9ef6.firebaseapp.com',
    storageBucket: 'finance-a9ef6.firebasestorage.app',
  );
}
